'BASE':
  name: get case
  request:
    url: https://postman-echo.com/get
    method: GET
    headers:
      Content-Type: application/json
      User-Agent: python-requests/2.18.4
  #log等级
  log_level: "debug"
  #扩展名
  log_extension: ".log"
  test:
    url: "https://demo-api.apipost.cn/api/demo"
  mobile: 18289454846
  ver_code: 123456

# 请求地址
urls:
  login: https://api.example.com/login
  get_user: https://api.example.com/users/{userid}

# 请求头
headers:
  Content-Type: application/json
  Authorization: Bearer xxx

# 账号信息
users:
  - username: test1
    password: 123456
  - username: test2
    password: 123456

# 登录请求数据
login_data:
  username: '{username}'
  password: '{password}'
#
## 用户ID列表
#user_ids: [1, 2, 3]
#
## 其他公共参数
#params:
#  pageSize: 20
#  timeout: 10000