'BASE':
  name: get case
  request:
    url: https://postman-echo.com/get
    method: GET
    headers:
      Content-Type: application/json
      User-Agent: python-requests/2.18.4
  #log等级
  log_level: "debug"
  #扩展名
  log_extension: ".log"
  #用户手机号、验证码
  mobile: 18289454846
  ver_code: 123456

# 请求地址
urls:
  url_news_login: https://demo-api.apipost.cn/api/demo/login
  url_news_datalist: https://demo-api.apipost.cn/api/demo/news_list?mobile=18289454846&theme_news=国际新闻&page=1&pageSize=20
  url_news_data: https://demo-api.apipost.cn/api/demo/news_list?mobile=18289454846&theme_news=国际新闻&page=1&pageSize=20
  url_news_collect: https://demo-api.apipost.cn/api/demo/collect_news
  url_news_talk: https://demo-api.apipost.cn/api/demo/news_comment?id=20&content=这篇文章写很棒!!
  url_news_delete: https://demo-api.apipost.cn/api/demo/delete_comment

# 请求头
headers:
  Content-Type: application/json
  Authorization: Bearer xxx

#data
news_talk:
  content: 这篇文章写很棒!!

# 账号信息
users:
  - username: test1
    password: 1234  56
  - username: test2
    password: 123456

# 登录请求数据
login_data:
  username: '{username}'
  password: '{password}'

#删除数据
news_delete:
  "id": 20
  "comment_id": 98
## 用户ID列表
#user_ids: [1, 2, 3]
#
## 其他公共参数
#params:
#  pageSize: 20
#  timeout: 10000